# Generated by Django 4.0.5 on 2022-10-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerange',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='attendancerange',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
