# Generated by Django 4.0.5 on 2022-06-19 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_options_alter_dept_options_class'),
        ('users', '0002_user_is_student_user_is_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.class'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.dept'),
            preserve_default=False,
        ),
    ]
