# Generated by Django 4.0.5 on 2022-06-19 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_options_alter_dept_options_class'),
        ('users', '0003_student_class_id_teacher_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.dept'),
        ),
    ]
