# Generated by Django 4.0.5 on 2022-06-19 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_teacher_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='class_id',
        ),
    ]
