# Generated by Django 4.0.5 on 2022-06-19 02:32

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_student_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234567890*$@', length=8, max_length=16, prefix='Tea_', primary_key=True, serialize=False),
        ),
    ]
