# Generated by Django 4.0.5 on 2022-06-19 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_class_id_alter_course_id_alter_dept_id'),
        ('users', '0007_alter_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='dept',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.dept'),
        ),
    ]
