# Generated by Django 4.0.5 on 2022-06-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_student_id_alter_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='DOB',
            field=models.DateField(default='1998-01-01'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='DOB',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
