# Generated by Django 4.0.5 on 2022-06-23 21:33

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='staff_no',
            field=models.IntegerField(default=users.models.ids, editable=False, unique=True, verbose_name='Code'),
        ),
    ]
