# Generated by Django 4.0.5 on 2022-06-26 18:04

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_teacher_staff_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='staff_no',
            field=models.IntegerField(default=users.models.ids, editable=False, unique=True, verbose_name='STAFF_ID'),
        ),
    ]
