# Generated by Django 4.0.5 on 2022-06-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_teacher_staff_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='col',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
