# Generated by Django 4.0.5 on 2022-06-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_teacher_col'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='col',
            field=models.CharField(max_length=50),
        ),
    ]
