# Generated by Django 4.0.5 on 2022-06-29 21:06

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_teacher_col'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='col',
            field=models.CharField(default=users.models.science_college, max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.CharField(default=1, editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
