# Generated by Django 4.0.5 on 2022-07-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.CharField(default=1, editable=False, max_length=30, primary_key=True, serialize=False),
        ),
    ]
