# Generated by Django 4.0.5 on 2022-07-17 17:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0022_alter_class_options'),
        ('users', '0026_alter_assigntime_period_attendanceclass_attendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.class'),
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
            options={
                'verbose_name_plural': 'Marks',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='MarksClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CAT 1', 'CAT 1'), ('CAT 2', 'CAT 2'), ('CAT 3', 'CAT 3'), ('SEMESTER EXAM', 'SEMESTER EXAM')], default='CAT 1', max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.assign')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('CAT 1', 'CAT 1'), ('CAT 2', 'CAT 2'), ('CAT 3', 'CAT 3'), ('SEMESTER EXAM', 'SEMESTER EXAM')], default='CAT 1', max_length=50)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('studentcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentcourse')),
            ],
        ),
    ]
