# Generated by Django 4.0.5 on 2022-07-19 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_course_dept'),
        ('users', '0027_attendancerange_student_class_id_studentcourse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.class'),
        ),
    ]
