# Generated by Django 4.0.5 on 2022-06-01 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_namse_teacher_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
