# Generated by Django 4.0.5 on 2022-06-19 02:22

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_id_alter_dept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=models.CharField(max_length=50), length=4, max_length=4, prefix='id_', primary_key=True, serialize=False),
        ),
    ]
