# Generated by Django 4.0.5 on 2022-06-19 02:28

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_dept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234567890*$@', length=4, max_length=16, prefix='id_', primary_key=True, serialize=False),
        ),
    ]
