# Generated by Django 4.0.5 on 2022-06-19 02:32

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_dept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234567890*$@', length=3, max_length=3, prefix='CL_', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234567890*$@', length=3, max_length=3, prefix='CO_', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dept',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234567890*$@', length=3, max_length=3, prefix='DEP_', primary_key=True, serialize=False),
        ),
    ]
