# Generated by Django 4.0.5 on 2022-06-21 17:53

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_class_id_alter_course_id_alter_dept_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefg1234567890*$@', length=5, max_length=6, prefix='CL_', primary_key=True, serialize=False),
        ),
    ]
