# Generated by Django 4.0.5 on 2022-07-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_remove_course_shortname'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='shortname',
            field=models.CharField(default='CE', max_length=20),
        ),
    ]
